### ISSUE TITLE
Missing files in MarkUs 

### ISSUE THREAD

**Issue by ptanugra** [alecjacobson/computer-graphics-final-image-competition#1]
We are supposed to submit 3 files right?  Currently in markus it is only README.MD.
Whereas we have 3 files for submission as indicated in the bottom of the repository.

**Comment by psarahdactyl** [comment]
You can submit either a video or an image, so I didn't specify a filename. You can submit files that are not listed this time!

**Comment by ptanugra** [comment]
Ah gotcha. Thanks and closing
